spring.application.name=barber-management-system
server.port=8080
server.servlet.context-path=/api
# MySQL Configuration (use environment variables for prod)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/barber-shop-mgmt?useSSL=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Logging - minimal logging in production
logging.level.root=WARN
logging.level.com.barbershop=INFO
logging.level.org.springframework.security=WARN

# JWT Configuration
jwt.secret=${JWT_SECRET}
# Access token expiration time in milliseconds (24 hours)
jwt.expiration=86400000
# Refresh token expiration time in milliseconds (7 days)
jwt.refresh-expiration=604800000

# File Upload
spring.servlet.multipart.max-file-size=10MB

